version: "2"
checks:
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 30
plugins:
  tslint:
    enabled: false
exclude_patterns:
  - "config/"
  - "dist/"
  - "release/"
  - "**/node_modules/"
  - "scripts/"
  - "**/test/"
  - "**/tests/"
  - "**/*.d.ts"
  - "**/*.generated.*"
