name: Release
on:
  push:
    branches:
      - release
jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn run rebuild-all-native
      - name: GQL Codegen
        run: yarn run gql-gen
      - name: Build and Release
        run: yarn run release
  MacOs:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      AC_USERNAME: ${{ secrets.AC_USERNAME }}
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn run rebuild-all-native
      - name: GQL Codegen
        run: yarn run gql-gen
      - name: Build and Release
        run: yarn run release

  Windows:
    runs-on: windows-2019
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          # The workaround below with node-gyp doesn't work for cached node installation
          node-version: "14.21.2"
          cache: "yarn"
      # See https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md
      # https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md
      - name: Update node-gyp
        run: |
          npm install --global node-gyp@8.x
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      - name: Update registry URL
        run: |
          npm config set registry "http://registry.npmjs.org"
          yarn config set registry "http://registry.npmjs.org"
          yarn config set network-timeout 300000
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn run rebuild-all-native
      - name: GQL Codegen
        run: yarn run gql-gen
      - name: Build and Release
        run: yarn run release
