name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    ## This is used to not re-run the build if only thoses files have changed
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18"
          cache: "yarn"
      # - name: Update node-gyp
      #   run: |
      #     npm install --global node-gyp@8.x
      #     npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline && yarn run rebuild-all-native
      - name: GQL Codegen
        run: yarn run gql-gen
      # - name: Lint
      #   run: yarn run lint:ci
      - name: Build
        run: yarn run build
  MacOs:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18"
          cache: "yarn"
      # - name: Update node-gyp
      #   run: |
      #     npm install --global node-gyp@8.x
      #     npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline && yarn run rebuild-all-native
      - name: GQL Codegen
        run: yarn run gql-gen
      # - name: Lint
      #   run: yarn run lint:ci
      - name: Tests
        run: yarn run test
      - name: Build
        run: yarn run build

  Windows:
    runs-on: windows-2019
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18"
          cache: "yarn"
      - name: Update node-gyp (windows only)
        if: startsWith(matrix.os, 'windows')
        run: |
          $WhereNode = Get-Command node | Select-Object -ExpandProperty Definition
          $NodeDirPath = Split-Path $WhereNode -Parent
          $NodeModulesPath = $NodeDirPath + "\node_modules\npm\node_modules\@npmcli\run-script"
          cd $NodeModulesPath
          npm install node-gyp@latest
      - name: Update registry URL
        run: |
          npm config set registry "http://registry.npmjs.org"
          yarn config set registry "http://registry.npmjs.org"
          yarn config set network-timeout 300000
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline && yarn run rebuild-all-native
      - name: GQL Codegen
        run: yarn run gql-gen
      # - name: Lint
      #   run: yarn run lint:ci
      - name: Tests
        run: yarn run test
      - name: Build
        run: yarn run build
